### ISSUE TITLE
Can ECONNRESET errors be retried?

### ISSUE THREAD

**Issue by jduan-highnote** [Codex-/await-remote-run#190]
See the screenshot. We get this error occasionally. Can some retry be added to this github action? Thanks!

<img width="2275" alt="CRISP-4822__add_cip_review_requester_and_decision_date_columns___12021__·_bay1inc_bayone_b153c8b" src="https://github.com/Codex-/await-remote-run/assets/92047874/63232e28-3859-44cc-a212-8dfd8f6269e2">

**Comment by Codex-** [comment]
Yup it certainly can be, I'll try take a look next week

**Comment by jduan-highnote** [comment]
No rush!

**Comment by jduan-highnote** [comment]
That was fast 💨

**Comment by Codex-** [comment]
No problem :)

Let me know if you see the issue again
