### ISSUE TITLE
Missing pagination support

### ISSUE THREAD

**Issue by omus** [Codex-/await-remote-run#207]
Seeing this failure on `v1.8.0`:
```
Error: getWorkflowId: An unexpected error has occurred: Failed to get Workflow ID for '<workflow>', available workflows: [<list of 30 workflows>]
Error: Failed: Failed to get Workflow ID for '<workflow>', available workflows: [<list of 30 workflows>]
Warning: Does the token have the correct permissions?
Error: Failed to get Workflow ID for '<workflow>', available workflows: [<list of 30 workflows>]
```
I believe the issue is probably lack of pagination support as the default results per page is 30.

**Comment by Codex-** [comment]
This repository does not contain `getWorkflowId`, I think you're referring to `return-dispatch`: https://github.com/Codex-/return-dispatch

Please open the issue there and we can go from there.

**Comment by omus** [comment]
I'll open an issue against: https://github.com/marketplace/actions/await-local-workflow-run

**Comment by omus** [comment]
https://github.com/Codex-/await-local-workflow-run/issues/143
