### ISSUE TITLE
Run ID Not Returning

### ISSUE THREAD

**Issue by jmosley5** [Codex-/await-remote-run#88]
Hello! I'm using your helpful guide to return the run_id and am having some issues. Included is a screenshot of the workflow. Any guidance or suggestions is appreciated. Thank you!
<img width="1245" alt="failedRunID" src="https://user-images.githubusercontent.com/12145163/174320435-470354e4-3570-4ffe-84b8-054e77025b5c.png">
(I've covered the run_id returned for privacy reasons but a run id is returned on the remote run

Issue: It looks like the Run ID is being identified but not being returned in the process

Scenario: 
On push Repo A is attempting to access and run the tests from  Repo B:

action.yml file for Repo A
```on:
  pull_request:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Dispatch and return Run ID
        uses: codex-/return-dispatch@v1.5.0
        id: return-dispatch
        with:
          token: ${{ secrets.ACCESS_TOKEN }} # Note this is NOT GITHUB_TOKEN but a PAT
          ref: {branch}
          repo: {repo}
          owner: {owner}
          workflow: ci.yml
          workflow_inputs: '{"cake":"delicious"}'
          workflow_timeout_seconds: 100 # Default: 300

      - name: Evaluate that the Run ID output has been set
        run: |
          if [ "${{ steps.return_dispatch.outputs.run_id }}" == "" ]; then
            echo "Failed to return Run ID"
            exit 1
          fi
    
      - name: Output fetched Run ID
        run: echo ${{ steps.return_dispatch.outputs.run_id }}
          
      - name: Await Run ID ${{ steps.return_dispatch.outputs.run_id }}
        uses: Codex-/await-remote-run@v1.4.0
        with:
          token: ${{ github.token }}
          repo: {repo}
          owner: {owner}
          run_id: ${{ steps.return_dispatch.outputs.run_id }}
          run_timeout_seconds: 300 # Optional
          poll_interval_ms: 5000 # Optional
  ```
  
 Repo B: Test file being accessed and return_id being requested:
 ```on:
  workflow_dispatch:
    inputs:
      distinct_id:
        required: true
      cake: # Test for input passthrough.
        required: true
  
  push:
jobs:
  test:
    name: run tests
    runs-on: ubuntu-latest
    env:
      E2E_TESTS_BASE_URL: ${{ secrets.ENV }}
    steps:
      - name: echo distinct ID ${{ github.event.inputs.distinct_id }}
        run: echo ${{ github.event.inputs.distinct_id }}
      - name: echo input passthrough
        run: echo ${{ github.event.inputs.cake }}

**Comment by jmosley5** [comment]
Actually, I think I fixed it? 😅 

I added workflow_run in Repo A and was able to return the run_id

```name: action.yml
on:
  pull_request:
  push:
  workflow_run:
    workflows: example.yml
    types:
      - completed
jobs:

**Comment by jmosley5** [comment]
Okay, I think I found what the issue is. The readme displays the following:

``` - name: Await Run ID ${{ steps.return_dispatch.outputs.run_id }}
    uses: Codex-/await-remote-run@v1.0.0
    with:
      token: ${{ github.token }}
      repo: return-dispatch
      owner: codex-
      run_id: ${{ steps.return_dispatch.outputs.run_id }}
 ```
 The `run_id` has an '_' underscore in `return-disptach`. I updated the code to use `steps.return-dispatch.outputs...` and it worked. 
 
Will you update the readme to reduce confusion for future users? 

Again, this is working great now. Thank you so much!

**Comment by Codex-** [comment]
Hi @jmosley5, 

I think your first post has mixed examples from both repositories, you should generally use an ID that makes sense for your repository.

Changing the id to be `return_dispatch` from `return-dispatch` would have fixed your missing outputs.

The current docs specify to use `return_dispatch` in a complete example: https://github.com/Codex-/await-remote-run/blob/main/README.md?plain=1#L23

Then you'll get the output you expect:
![image](https://user-images.githubusercontent.com/8297838/174414443-3c879901-0897-4435-b65c-c7da88c86357.png)

> The `run_id` has an '_' underscore in `return-disptach`. I updated the code to use `steps.return-dispatch.outputs...` and it worked.

The `run_id` is meant to have an underscore: https://github.com/Codex-/return-dispatch/blob/main/action.yml#L8

Did you mean to refer to the step ID? 

> Will you update the readme to reduce confusion for future users?

I've updated the `return-dispatch` readme so that it uses the same ID's that are used in `await-remote-run`
